# Generated by The Deployer. Safe to regenerate.
FROM node:20-slim AS build
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm ci || npm install
COPY . .
RUN npm run build
RUN mkdir -p /out && (cp -r dist/* /out/ 2>/dev/null || cp -r build/* /out/)
FROM nginx:alpine
COPY --from=build /out /usr/share/nginx/html
RUN printf 'server { listen 80; root /usr/share/nginx/html; location / { try_files $uri $uri/ /index.html; } }' > /etc/nginx/conf.d/default.conf
EXPOSE 80
